### ISSUE TITLE
Restore the XP bottle quest

### ISSUE THREAD

**Issue by FlaggAC** [FlaggAC/ACE#1]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
The XP bottle quest does not spawn a boss at the end. 

### Desired functionality.
1. Ensure that the boss spawns.
2. Ensure that the XP bottle drops from the boss
3. Ensure that the XP bottle functions as intended.
4. Ensure that XP bottle does not gain XP from vassal passup, and ensure that using the XP bottle does not pass up XP to patron
5. Take a database dump of all existing XP bottles, and the owners of them

**Comment by Unknown01glitch** [comment]
if current WCID is being used for xp bottle. it gains xp on kill and does not gain xp from vassal pass-up it will also not gain xp from vassal using an xp bottle or from any turn ins.

**Comment by magemasterII** [comment]
I checked it as well, gains 16.666% xp from only direct kills, splits equally among all bottles in the inventory. Doesn't gain any vassal passup xp and when using the bottle it doesn't pass any xp up to your patron.

The xp bottle is earned from turning in the quest item that drops from boss, the boss properly drops the quest item but the boss generator is currently missing from the final room.
