### ISSUE TITLE
Make set epics drop from all t6+ mobs

### ISSUE THREAD

**Issue by FlaggAC** [FlaggAC/ACE#10]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
(Needs further specification)

**Comment by magemasterII** [comment]
Epics already drop from all t7 mobs, just change tier in LootGenerationFactory_Clothing to >6 instead of >7 and sets will drop on t7 as well, see commit above.

**Comment by FlaggAC** [comment]
https://docs.google.com/spreadsheets/d/1gsLVaGL9HM_U62VvbctbkTLfXkEn8agWcYuk-8xC6Xo/edit#gid=0
