### ISSUE TITLE
Aetheria Surges not working as intended

### ISSUE THREAD

**Issue by PotatoNPK** [FlaggAC/ACE#22]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Protection surges dont seem to be working correctly upon proc.

### Desired functionality.
work as intended

### Mention any other details that might be useful.
was reported in Riptide general chat, that our(potato's) surges are not working correctly. Mage has investigated briefly and thinks it maybe an issue with the spells that proc not being in game possibly?

**Comment by magemasterII** [comment]
All surges ARE working on the Dev server, though the properties using @propertydump don't show changes to rating(not sure if theyre intended to), the damage being done is correctly being altered by surges of protection & destruction, affliction and regeneration working as well, festering showing up but difficult to confirm effects, 99% sure its working based on spell data.
Checked Sigil buffs as well and those are properly working into the damage events as well.
Can't confirm its the same on the main server but 100% working on the dev server.

Only possible issue is at what %/RNG the procs are triggering and how close it is to retail but it seems to be RNGing frequently enough to be useful but not OP as it is.
