### ISSUE TITLE
Fetish of the Dark Idols doesnt apply to weapons that have been imbued or tinkered

### ISSUE THREAD

**Issue by PotatoNPK** [FlaggAC/ACE#25]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
you can apply the Fetish of the Dark Idols to weapons that have not been tinkered. but if you try to apply to one that has been fully tinkered it says failed to apply.

### The log given by the failure.
NA

### Desired functionality.
Find root cause, Fetish of the Dark Idols should apply to all loot missile weapons, tinkers should not matter.

### Mention any other details that might be useful.
reported first by Dragonwolf

**Comment by FlaggAC** [comment]
Fixed, but Dragonwolf should confirm
