### ISSUE TITLE
Westshore Mansion Hooks Not Working?

### ISSUE THREAD

**Issue by magemasterII** [FlaggAC/ACE#30]
Dobby & Bad Karma reported that the hooks on their mansion Westshores weren't working even though they used the hooks open command. They couldn't change what was inside of them. Unable to confirm the problem on Mage on the main server.

Mage bought the mansion on Dev server using the @purchase-house command and was able to use and open the hooks with no problem.

https://asheron.fandom.com/wiki/Far_West_Shores_Mansion ? Not sure if this is the correct mansion.

**Comment by FlaggAC** [comment]
I looked into it and also didn't find a problem. Advised Darkbeat to use the command /house hook on and to try using the Darkbeat character (mansion owner) to open the hook. Will re-open if there are further issues
