### ISSUE TITLE
Re-Enable Massive Mana Charge as viable death item

### ISSUE THREAD

**Issue by FlaggAC** [FlaggAC/ACE#5]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality.
Buying a massive mana charge from the vendor should cost the same as it did in retail. And they should drop on death, functioning as viable death items as they did in retail.

**Comment by magemasterII** [comment]
Modify DeathItemCategory.None to DeathItemCategory.ManaStone in DeathItem.cs, see commit above.
