### ISSUE TITLE
Defense of Zaikhal quest reported to not give adjusted experience based on server-wide xp multiplier

### ISSUE THREAD

**Issue by FlaggAC** [FlaggAC/ACE#7]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps.
Turn in the medallion from https://asheron.fandom.com/wiki/Defense_of_Zaikhal_(Platinum)
Experience given should be 58x3 = 174 million. Instead it is the baseline of 58 million

### Mention any other details that might be useful.
This is still unconfirmed

Additionally, make sure it's fixed for all quests that use this calculation - The one listed here is merely an example, not the only case of it.

**Comment by magemasterII** [comment]
Modify the award giving NPC weenie Jun Sawashima 31692.  AwardLevelProportionalXP gives the amount listed based on level, AwardXP or AwardNoShareXP seem to work with the server xp multiplier. Though a number of quests use the AwardLevelProportionalXP type so all of them won't give the multiplier as well.

Can't really be called an issue and in question is whether we want to change the reward xp for however many quests.

**Comment by PotatoNPK** [comment]
as mage said, this is working as intended. the player report was inaccurate. based on XP recieved/given
